### ISSUE TITLE
Plugged controller didn't work after GC HW2

### ISSUE THREAD

**Issue by NeoRame** [nostalgic-indulgences/BlueRetro_Internal_Installation#1]
After GC HW2 mod, the port detection work and plugged controller didn't work anymore. 

The mod with wireless controller works fine.

May I used wrong resistors? I used 103 0805 SMD.

![image](https://user-images.githubusercontent.com/3717141/201729755-be07aaa6-38e6-4b49-8a2c-3ff285064601.jpeg)

**Comment by NeoRame** [comment]
And if I plug a controller, the wireless one didn't work to until I unplug the wired one

**Comment by nostalgic-indulgences** [comment]
I don't quite understand the issue here... it seems like it's doing exactly what it was supposed to do. i.e. With a wireless controller connected to Port 1, plugging in a physical controller to Port 1 will switch the P1 wireless to P2. Furthermore, did you pay attention to this?
![2022-11-15 10_31_39-Window](https://user-images.githubusercontent.com/112358096/201812101-8f9fa315-6218-46de-bd82-3001344f73f9.png)

**Comment by NeoRame** [comment]
And that's my problem. The wired controller didn't work, the wireless didn't switch and stop working till the wired one is unplugged.

And yes I bridged the vn to 3,3 

I will open my GC later to double check and do more photos

Edit: lol I saw i have a typo in the main post 😂

**Comment by nostalgic-indulgences** [comment]
While you are at it, make sure you use your multi-meter to ensure the port shield traces are severed properly. Controller plug shielding must be totally isolated from the console GND for effective port detection.

**Comment by NeoRame** [comment]
That's I already check while I cut the ground. But I triple check that ;)

**Comment by NeoRame** [comment]
I checked it twice now.

-All shields disconnected from ground
-3.3 connected to shields with 10k resistor
-all lines are solid and no shorts
On esp:
-VN bridged with 3.3
-EN and 3.3 connected with 10k resistor![image](https://user-images.githubusercontent.com/3717141/202013340-5dda2028-6c41-4601-84fb-b90471ca97cb.jpeg)

**Comment by NeoRame** [comment]
I resoldering all connection at 3.3 and VN and so on. Same problems: wired controller didn't work anymore. And if a wired controller is connected, the wireless stop working/ the esp can't connect to a wireless controller


![image](https://user-images.githubusercontent.com/3717141/202024679-1cf791b8-27c7-479b-841e-b95a483d6e36.jpeg)

![image](https://user-images.githubusercontent.com/3717141/202024699-4d30ecab-7c7a-4e0b-8f77-0e1909112ce4.jpeg)

![image](https://user-images.githubusercontent.com/3717141/202024759-8f943ca7-6255-42ee-b4c5-d31fa8641b7b.jpeg)

**Comment by NeoRame** [comment]
Ahhhh and maybe it helps, I flashed the BlueRetro_gc_external from 1.7.3

**Comment by NeoRame** [comment]
ok, i think you can forget everything i said.... i run the wrong firmware! i desolder the esp and flash the 1,8 beta -.-

**Comment by NeoRame** [comment]
i'm back XD

ok now i'm a step closer. i update to v1.8-rc4 hw2. 
Now a wired controller work IF no Wireless is connected and vice versa. that also means i cant use wired and wireless at the same time... and the port detection "didn't" work

**Comment by nostalgic-indulgences** [comment]
Have you paid particular attention to this?

![B5C689AC-F621-4C80-9DF2-50B9C462E450](https://user-images.githubusercontent.com/112358096/202088438-588bbc06-cfba-435a-9f4e-f768673f4189.jpeg)

Furthermore, shield detection will only work with physical controllers with their plug connector shielding connected to ground - ie original GameCube controllers.

**Comment by NeoRame** [comment]
yes i did. 
soldered a button to 32E, reset the ESP and flash the ESP with USB. Web Config said 1.8 beta...
Today, i used the Web Config Beta to Reset a second time and push the 1.8 Beta OTA but with the same result

-Wireless work fine
-Physical wired Controller work fine,too
- both together didnt work till one of the other controller is disconncted.

but unfortunately i dont have original Controller here. i only own an after market wireless controller, an after original look alike controller and a no name after market controller.

**Comment by NeoRame** [comment]
I hate my life!!!! XD

now i try my last (untested) third party controller AND and GBA Controller Cable.......

AND IT WORKS!!!!! Thank you so much for this work and for your patience!!!!

AWESOME MOD!!!! Thank you thank you thank you! now i need an original controller XD

**Comment by nostalgic-indulgences** [comment]
:) Glad it worked out for you eventually. You can physically mod your 3rd party controllers as well by bridging the shielding wire to ground from within the controller itself.
